DonutQueen/ViewModels/GrantPermissionViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DonutQueen.ViewModels
{
    public class GrantPermissionViewModel
    {
        public SelectList Gebruikers { get; set; }
        public SelectList Rollen { get; set; }
        public string GebruikerId { get; set; }
        public string RolId { get; set; }
    }
}

DonutQueen/Controllers/GebruikerController.cs
using DonutQueen.Areas.Identity.Data;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace DonutQueen.Controllers
{
    [Authorize(Roles ="admin")]
    public class GebruikerController : Controller
    {
        private UserManager<CustomUser> _userManager;
        private RoleManager<IdentityRole> _roleManager;

        public GebruikerController(UserManager<CustomUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            GebruikerListViewModel viewModel = new GebruikerListViewModel()
            {
                Gebruikers = _userManager.Users.ToList()

            };
            return View(viewModel);
        }

        public IActionResult Edit(string id)
        {
            CustomUser gebruiker =  _userManager.Users.Where(k => k.Id == id).FirstOrDefault();

            
            if (gebruiker != null)
            {
                GebruikerEditViewModel viewModel = new GebruikerEditViewModel()
                {
                    GebruikerId = gebruiker.Id,
                    Naam = gebruiker.Naam,
                    Voornaam = gebruiker.Voornaam,
                    Email = gebruiker.UserName,
                    Geboortedatum = gebruiker.Geboortedatum,
 
                };
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(GebruikerEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                CustomUser gebruiker = await _userManager.FindByIdAsync(viewModel.GebruikerId);

                gebruiker.Naam = viewModel.Naam;
                gebruiker.Voornaam = viewModel.Voornaam;
                gebruiker.Geboortedatum = viewModel.Geboortedatum;
                gebruiker.Email = viewModel.Email;
                
                IdentityResult result = await _userManager.UpdateAsync(gebruiker);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }

        public IActionResult Create()
        {
            GebruikerCreateViewModel viewModel = new GebruikerCreateViewModel()
            {
                Geboortedatum = new DateTime(1950, 1, 1),
                Rollen = new SelectList(_roleManager.Roles.ToList(), "Id", "Name")
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(GebruikerCreateViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                CustomUser gebruiker = new CustomUser
                {
                    Naam = viewModel.Naam,
                    Voornaam = viewModel.Voornaam,
                    Geboortedatum = viewModel.Geboortedatum,
                    UserName = viewModel.Email,
                    Email = viewModel.Email
                };

                IdentityResult result = await _userManager.CreateAsync(gebruiker, viewModel.Password);

                if (result.Succeeded)
                {
                    CustomUser user = await _userManager.FindByEmailAsync(viewModel.Email);
                    IdentityRole role = await _roleManager.FindByIdAsync(viewModel.RolId);

                    IdentityResult Resultaat = await _userManager.AddToRoleAsync(user, role.Name);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
                }
            }
            return View(viewModel);
        }


        public async Task<IActionResult> Delete(string id)
        {
            CustomUser user = await _userManager.FindByIdAsync(id);
   
            if (user == null)
            {
                return NotFound();
            }

            GebruikerDeleteViewModel viewModel = new GebruikerDeleteViewModel()
            {
                GebruikerId = id,
                Voornaam = user.Voornaam,
                Naam = user.Naam
            };
            return View(viewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(string id)
            {
            CustomUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View("Index", _userManager.Users.ToList());
        }

        //[AllowAnonymous]
        public IActionResult GrantPermissions()
        {
            GrantPermissionViewModel viewModel = new GrantPermissionViewModel()
            {
                Gebruikers = new SelectList(_userManager.Users.ToList(), "Id", "UserName"),
                Rollen = new SelectList(_roleManager.Roles.ToList(), "Id", "Name")
            };
            return View(viewModel);
        }

        //[AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GrantPermissions(GrantPermissionViewModel viewModel)
        {                                                 
            if (ModelState.IsValid)
            {
                CustomUser user = await _userManager.FindByIdAsync(viewModel.GebruikerId);
                IdentityRole role = await _roleManager.FindByIdAsync(viewModel.RolId);
                if (user != null && role != null)
                {
                    IdentityResult result = await _userManager.AddToRoleAsync(user, role.Name);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        foreach (IdentityError error in result.Errors)
                            ModelState.AddModelError("", error.Description);
                    }
                }
                else
                    ModelState.AddModelError("", "User or role Not Found");
            }
            return View(viewModel);
        }

    }
    
}

DonutQueen/Views/Gebruiker/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DonutQueen.ViewModels.GebruikerCreateViewModel
@{
    ViewData["Title"] = "Create";
}
<p></p>
<h2>Nieuwe gebruiker aanmaken</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voornaam" class="control-label"></label>
                <input asp-for="Voornaam" class="form-control" />
                <span asp-validation-for="Voornaam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Geboortedatum" class="control-label"></label>
                <input asp-for="Geboortedatum" class="form-control" />
                <span asp-validation-for="Geboortedatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <select asp-for="RolId" asp-items="Model.Rollen"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary" />
                <a asp-controller="Gebruiker" asp-action="Index" class="btn btn-primary">Terug</a>
            </div>
        </form>
    </div>

</div>
<div>

</div>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

DonutQueen/Views/Gebruiker/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DonutQueen.ViewModels.GebruikerDeleteViewModel
@{
    ViewData["Titel"] = "Delete";
}
<p></p>
<h4> Ben je zeker dat je @Model.Voornaam @Model.Naam wil verwijderen?</h4>
<form asp-action="Delete">
    <input type="hidden" asp-for="GebruikerId" />
    <input type="submit" value="Delete" class="btn btn-primary" />
    <a asp-action="Index">Back to List</a>

</form>

DonutQueen/Views/Gebruiker/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DonutQueen.ViewModels.GebruikerEditViewModel
@{
    ViewData["Title"] = "Edit";
}

<p></p>
<h2>@Model.Voornaam @Model.Naam wijzigen</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voornaam" class="control-label"></label>
                <input asp-for="Voornaam" class="form-control" />
                <span asp-validation-for="Voornaam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Geboortedatum" class="control-label"></label>
                <input asp-for="Geboortedatum" class="form-control" />
                <span asp-validation-for="Geboortedatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="GebruikerId" class="form-control" hidden />
                <input type="submit" value="Wijzigen" class="btn btn-primary" />
                <a asp-controller="Gebruiker" asp-action="Index" class="btn btn-primary">Terug</a>
            </div>
        </form>
    </div>

</div>
<div>
</div>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

DonutQueen/Views/Gebruiker/GrantPermissions.cshtml
@model DonutQueen.ViewModels.GrantPermissionViewModel

@{
    ViewData["Title"] = "Grant Permission";
}

<form asp-action="GrantPermissions" asp-method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <select asp-for="GebruikerId" asp-items="Model.Gebruikers"></select>
    </div>
    <div class="form-group">
        <select asp-for="RolId" asp-items="Model.Rollen"></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

DonutQueen/Views/Gebruiker/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model DonutQueen.ViewModels.GebruikerListViewModel
@{
    ViewData["Title"] = "Index";
}
<h2> Gebruikers</h2>
<p>
    <a asp-action="Create"> Nieuwe gebruiker aanmaken</a>
</p>

<table>
    <thead>
        <tr>
        <th class="col-md-4">
            @Html.DisplayNameFor(v => v.Gebruikers[0].Naam)
        </th>
        <th class="col-md-4">
            @Html.DisplayNameFor(v => v.Gebruikers[0].Voornaam)
        </th>

    <th class="col-md-4">
            @Html.DisplayNameFor(v => v.Gebruikers[0].Email)
    </th>
    </tr>
    </thead>
    <tbody>
        @foreach(var gebruiker in Model.Gebruikers){
            <tr>
                <td class="col-md-4">
                    @Html.DisplayFor(modelitem => gebruiker.Naam)
                </td>
                <td class="col-md-4">
                    @Html.DisplayFor(modelitem => gebruiker.Voornaam)
                </td>

                <td class="col-md-4">
                    @Html.DisplayFor(modelitem => gebruiker.Email)
                </td>
                <td class="col-md-4">
                    <a asp-action="Edit" asp-route-id="@gebruiker.Id">Wijzigen</a>

                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@gebruiker.Id">Verwijderen</a>
                </td>
            </tr>
             }
    </tbody>
</table>