DonutQueen/Controllers/AdminController.cs
using DonutQueen.Areas.Identity.Data;
using DonutQueen.Data;
using DonutQueen.Models;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using WinkelDonut = DonutQueen.Models.WinkelDonut;

namespace DonutQueen.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IUnitOfWork _uow;

        // DI injectie UOW
        public AdminController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        public IActionResult Donuts()
        {
            DonutOverviewViewModel vm = new DonutOverviewViewModel()
            {
                Donuts = _uow.DonutRepository.GetAll().ToList()
            };

            return View(vm);
        }

        public async Task<IActionResult> DonutDetails(int id)
        {
            Donut donut = await _uow.DonutRepository.GetById(id);
            if (donut != null)
            {
                DonutDetailsViewModel vm = new DonutDetailsViewModel()
                {
                    DonutId = id,
                    Naam = donut.Naam,
                    Topping = donut.Topping,
                    Glazuur = donut.Glazuur,
                    Vulling = donut.Vulling,
                    Omschrijving = donut.Omschrijving,
                    IsVegan = donut.IsVegan,
                    Afbeelding = donut.Afbeelding,
                    Prijs = donut.Prijs
                };

                return View(vm);
            }
            else
            {
                DonutOverviewViewModel vm = new DonutOverviewViewModel()
                {
                    Donuts = _uow.DonutRepository.GetAll().ToList()
                };
                return View("Index", vm);
            }
        }

        [HttpGet]
        public IActionResult CreateDonut()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDonut(CreateDonutViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Donut donut = new Donut()
                {
                    Naam = viewModel.Naam,
                    Topping = viewModel.Topping,
                    Glazuur = viewModel.Glazuur,
                    Vulling = viewModel.Vulling,
                    Omschrijving = viewModel.Omschrijving,
                    IsVegan = viewModel.IsVegan,
                    Afbeelding = viewModel.Afbeelding,
                    Prijs = viewModel.Prijs
                };
                _uow.DonutRepository.Create(donut);
                await _uow.Save();
                return RedirectToAction(nameof(Donuts));
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditDonut(int? id)
        {
            if (id == null)
                return NotFound();

            int meegegevenId = (int)((id != null) ? id : 0);
            Donut donut = await _uow.DonutRepository.GetById(meegegevenId);

            if (donut == null)
                return NotFound();

            EditDonutViewModel vm = new EditDonutViewModel()
            {
                DonutId = donut.DonutId,
                Naam = donut.Naam,
                Topping = donut.Topping,
                Glazuur = donut.Glazuur,
                Vulling = donut.Vulling,
                Omschrijving = donut.Omschrijving,
                IsVegan = donut.IsVegan,
                Afbeelding = donut.Afbeelding,
                Prijs = donut.Prijs
            };

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditDonut(int id, EditDonutViewModel viewModel)
        {
            if (id != viewModel.DonutId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Donut donut = new Donut()
                    {
                        DonutId = viewModel.DonutId,
                        Naam = viewModel.Naam,
                        Topping = viewModel.Topping,
                        Glazuur = viewModel.Glazuur,
                        Vulling = viewModel.Vulling,
                        Omschrijving = viewModel.Omschrijving,
                        IsVegan = viewModel.IsVegan,
                        Afbeelding = viewModel.Afbeelding,
                        Prijs = viewModel.Prijs
                    };
                    _uow.DonutRepository.Update(donut);
                    await _uow.Save();
                }
                catch (DbUpdateConcurrencyException e)
                {
                    if (_uow.DonutRepository.GetById(viewModel.DonutId) == null)
                        return NotFound();
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Donuts));
            }
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteDonut(int id)
        {
            Donut donut = await _uow.DonutRepository.GetById(id);
            if (donut != null)
            {
                DeleteDonutViewModel vm = new DeleteDonutViewModel()
                {
                    DonutId = id,
                    Naam = donut.Naam,
                    Topping = donut.Topping,
                    Glazuur = donut.Glazuur,
                    Vulling = donut.Vulling,
                    Omschrijving = donut.Omschrijving,
                    IsVegan = donut.IsVegan,
                    Afbeelding = donut.Afbeelding,
                    Prijs = donut.Prijs
                };

                return View(vm);
            }
            else
            {
                DonutOverviewViewModel vm = new DonutOverviewViewModel()
                {
                    Donuts = _uow.DonutRepository.GetAll().ToList()
                };
                return View("Index", vm);
            }
        }

        [HttpPost, ActionName("DeleteDonut")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteDonutConfirm(int id)
        {
            Donut donut = await _uow.DonutRepository.GetById(id);
            _uow.DonutRepository.Delete(donut);
            await _uow.Save();
            return RedirectToAction(nameof(Donuts));
        }

        public IActionResult LeverancierLijst()
        {
            LeverancierOverviewViewModel vm = new LeverancierOverviewViewModel()
            {
                Leveranciers = _uow.LeverancierRepository.GetAll().ToList()
            };

            return View(vm);
        }

        public IActionResult DonutPerLeverancier()
        {
            //  In view binnen de associatie-info, hebben we Leverancier & Donut object nodig
            var ld = _uow.LeverancierDonutRepository.GetAll(x => x.Leverancier, y => y.Donut).ToList();
            DonutsPerLeverancierViewModel pdvm = new DonutsPerLeverancierViewModel();
            pdvm.LeverancierDonuts = ld;

            return View(pdvm);
        }

        public IActionResult Winkels()
        {
            WinkelOverviewViewModel vm = new WinkelOverviewViewModel()
            {
                Winkels = _uow.WinkelRepository.GetAll().ToList()
            };

            return View(vm);
        }

        public IActionResult Gebruikers()
        {
            return View();
        }

        public IActionResult Orders()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> BeschikbaarheidAanpassen(int id, BeschikbaarheidAanpassenViewModel vm)
        {

            Winkel winkel = await _uow.WinkelRepository.GetById(id);

            if (winkel != null)
            {
                vm.WinkelId = id;
                vm.Winkelnaam = winkel.Naam;
                 
                vm.Donuts = new List<SelectListItem>();
                foreach (var p in _uow.DonutRepository.GetAll())
                {
                    if (vm.DonutId == p.DonutId)
                    {
                        vm.Donuts.Add(new SelectListItem() { Text = p.Naam, Value = p.DonutId.ToString(), Selected = true });

                        WinkelDonut wd = _uow.WinkelDonutRepository.GetAll().Where(d => d.Winkelid == id && d.DonutId == p.DonutId).FirstOrDefault();

                        if (wd != null)
                        { vm.Hoeveelheid = wd.Hoeveelheid; }
                        else
                        { vm.Hoeveelheid = 0; }
                     }
                    else
                    {
                        vm.Donuts.Add(new SelectListItem() { Text = p.Naam, Value = p.DonutId.ToString(), Selected = false });
                    }

                }
                return View(vm);
            }
            else
            { 
            WinkelOverviewViewModel viewmodel = new WinkelOverviewViewModel()
            {
                Winkels = _uow.WinkelRepository.GetAll().ToList()
            };

            return View("Winkels",viewmodel);
            }

        }

        [HttpPost]

        public async Task<IActionResult> BeschikbaarheidAanpassen(BeschikbaarheidAanpassenViewModel vm)
        {
            if (ModelState.IsValid)
            {
                try
                {

DonutQueen/Controllers/ShopController.cs
using DonutQueen.Data;
using DonutQueen.Models;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;

namespace DonutQueen.Controllers
{
    public class ShopController : Controller
    {
        private readonly IUnitOfWork _uow;

        // DI injectie UOW
        public ShopController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        public IActionResult Index()
        {
            ShopViewModel vm = new ShopViewModel()
            {
                Donuts = _uow.DonutRepository.GetAll().ToList()
            };

            return View(vm);
        }

        public async Task<IActionResult> Details(int id)
        {

            Donut donut = await _uow.DonutRepository.GetById(id);

            ShopDetailsViewModel vm = new ShopDetailsViewModel()
            {
                Naam = donut.Naam,
                Topping = donut.Topping,
                Glazuur = donut.Glazuur,
                Vulling = donut.Vulling,
                Omschrijving = donut.Omschrijving,
                IsVegan = donut.IsVegan,
                Afbeelding = donut.Afbeelding,
                Prijs = donut.Prijs
            };

            return View(vm);
        }

    }
}

DonutQueen/Controllers/WinkelController.cs
using DonutQueen.Data;
using DonutQueen.Models;
using DonutQueen.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace DonutQueen.Controllers
{
    public class WinkelController : Controller
    {
        private readonly IUnitOfWork _uow;

        // DI injectie UOW
        public WinkelController(IUnitOfWork uow)
        {
            _uow = uow;
        }
        public IActionResult Index()
        {
            WinkelsViewModel vm = new WinkelsViewModel()
            {
                Winkels = _uow.WinkelRepository.GetAll().ToList()
            };

            return View(vm);
        }
        public IActionResult Beschikbaarheid(int id)
        {
            BeschikbaarheidViewModel viewModel = new BeschikbaarheidViewModel();

            viewModel.WinkelDonuts = _uow.WinkelDonutRepository.GetAll(x => x.Donut, y => y.Winkel).Where(z => z.Winkelid == id).ToList();
            viewModel.Winkelnaam = _uow.WinkelRepository.GetAll().Where(a => a.WinkelId == id).FirstOrDefault().Naam;
            return View(viewModel);
        }
    }
}

DonutQueen/Views/Shared/_DonutQueenLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DonutQueen - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/donutqueen.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo_dq.png" width="45" height="45" alt="Logo Donut Queen">
                    Donut Queen
                </a>
                <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarCustom">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarCustom">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Winkel" asp-action="Index">Onze winkels</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Admin </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Donuts">Donuts</a>
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Winkels">Winkels</a>
                                    <a class="dropdown-item" asp-controller="Gebruiker" asp-action="Index">Gebruikers</a>
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Orders">Orders</a>
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="LeverancierLijst">Leveranciers</a>
                                </div>

                            </li>
                        }
                            <partial name="_LoginPartial">
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DonutQueen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    <script>
        $.validator.methods.range = function (value, element, param) { var globalizedValue = value.replace(",", "."); return this.optional(element) || (globalizedValue >= param[0] && globalizedValue <= param[1]); }
        $.validator.methods.number = function (value, element) { return this.optional(element) || /-?(?:\d+|\d{1,3}(?:[\s\.,]\d{3})+)(?:[\.,]\d+)?$/.test(value); }
        $.validator.methods.date = function (value, element) { var date = value.split("/"); return this.optional(element) || !/Invalid|NaN/.test(new Date(date[2], date[1], date[0]).toString()); }
    </script>
</body>
</html>

DonutQueen/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonutQueen</title>
    <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Identity/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/">DonutQueen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                    }
                    @if (result.Success)
                    {
                        await Html.RenderPartialAsync("_LoginPartial");
                    }
                    else
                    {
                        throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                            "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                            $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2022 - DonutQueen - <a asp-area="" asp-page="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/Identity/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>